source 'http://rubygems.org'

gem 'rails', '3.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

gem "authlogic", :git => "git://github.com/odorcicd/authlogic.git", :branch => "rails3"
gem "authlogic-connect"
gem "haml"
gem "oauth"
gem "oauth2"
gem "pg"
gem "rack-openid", ">=0.2.1", :require => "rack/openid"
gem "ruby-openid"
gem "signet"

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
