var CANVAS_WIDTH = 640;
var CANVAS_HEIGHT = 480;

var GRAVITY = 0.8;
var MILLISECONDS_PER_FRAME = 33;

var DEVELOPMENT = false;

var SPRAY_EFFECTS_ENABLED = false;

var SOUND_EFFECTS_ENABLED = false;

var MUSIC_ENABLED = true;
